### ISSUE TITLE
Expand text to dynamically match table width?

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/risk-data-library.github.io#78]
![Screen Shot 2020-09-30 at 09 30 36](https://user-images.githubusercontent.com/10201533/94656144-f7aa9600-02ff-11eb-977c-e6b6b7ca86ac.jpg)

**Comment by stufraser1** [comment]
Being addressed via Trello
https://trello.com/c/UM1RUIP2/112-extend-width-of-table-description-paragr
